---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  namespace: argocd
  labels:
    name: prometheus-operator-crds
spec:
  project: infra-apps
  source:
    repoURL: https://prometheus-community.github.io./helm-charts
    chart: prometheus-operator-crds
    targetRevision: 30.0.1
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PreserveResourcesOnDeletion=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
