---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openobserve
  namespace: openobserve
  labels:
    name: openobserve
spec:
  project: infra-apps
  source:
    repoURL: https://charts.openobserve.ai
    chart: openobserve
    targetRevision: 0.80.3
  destination:
    name: in-cluster
    namespace: openobserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PreserveResourcesOnDeletion=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
